### ISSUE TITLE
selamlar, hesap yanlis gibi duruyor

### ISSUE THREAD

**Issue by enesusta** [hamitaksln/hamitaksln.github.io#4]
600 bin lira icin yaptigim hesap: 
![Screen Shot 2024-06-21 at 12 53 01](https://github.com/hamitaksln/hamitaksln.github.io/assets/32740550/7cf41487-76a2-4798-83e6-1d4ff9aba6b0)

fakat olmasi gereken tutar:
![Screen Shot 2024-06-21 at 12 53 29](https://github.com/hamitaksln/hamitaksln.github.io/assets/32740550/8f68c204-d33f-46a3-b50b-bfcbe76af586)

bir diger siteden:
![Screen Shot 2024-06-21 at 12 53 55](https://github.com/hamitaksln/hamitaksln.github.io/assets/32740550/5d9280fa-caa7-44c3-adfd-9979b696c0d7)

**Comment by hamitaksln** [comment]
Merhabalar. 600bin yerine 600 milyon yazmışsınız. Kolaylık olması açısından
yüzbin sıfırlarını uygulama kendisi ekliyor. Ona dikkat edip tekrar
denerseniz sevinirim. Eğer hala yanlışsa inceleme yapayım.

Gmail Mobil'den gönderildi

**Comment by enesusta** [comment]
tesekkur ederim, evet sifir ekleme mevzuu yuzunden bi karisiklik olmus. ellerine saglik
